# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pong_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setStyleSheet("*{\n"
"    border:none;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_body = QtWidgets.QWidget(self.centralwidget)
        self.main_body.setMinimumSize(QtCore.QSize(600, 600))
        self.main_body.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main_body.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.main_body.setObjectName("main_body")
        self.gridLayout = QtWidgets.QGridLayout(self.main_body)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.holder_frame = QtWidgets.QFrame(self.main_body)
        self.holder_frame.setStyleSheet("background-color: rgba(0, 0, 0,0);")
        self.holder_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.holder_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.holder_frame.setObjectName("holder_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.holder_frame)
        self.gridLayout_2.setContentsMargins(200, 180, 200, 180)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttons_holder = QtWidgets.QFrame(self.holder_frame)
        self.buttons_holder.setMinimumSize(QtCore.QSize(0, 150))
        self.buttons_holder.setMaximumSize(QtCore.QSize(300, 300))
        self.buttons_holder.setStyleSheet("background-color: rgba(255, 255, 127,0);")
        self.buttons_holder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_holder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_holder.setObjectName("buttons_holder")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_holder)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_play = QtWidgets.QPushButton(self.buttons_holder)
        self.btn_play.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(16, 2, 171);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(18, 1, 116);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 26pt \"Arial\";\n"
"    border: 6px solid rgb(13, 1, 90);\n"
"    \n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"")
        self.btn_play.setObjectName("btn_play")
        self.verticalLayout.addWidget(self.btn_play)
        self.btn_custom = QtWidgets.QPushButton(self.buttons_holder)
        self.btn_custom.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_custom.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_custom.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(67, 69, 204);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(18, 1, 116);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 26pt \"Arial\";\n"
"    border: 6px solid rgb(13, 1, 90);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.btn_custom.setObjectName("btn_custom")
        self.verticalLayout.addWidget(self.btn_custom)
        self.btn_quit = QtWidgets.QPushButton(self.buttons_holder)
        self.btn_quit.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_quit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_quit.setStyleSheet("QPushButton:hover{\n"
"    \n"
"    background-color: rgb(67, 69, 204);\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(18, 1, 116);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 26pt \"Arial\";\n"
"    border: 6px solid rgb(13, 1, 90);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.btn_quit.setObjectName("btn_quit")
        self.verticalLayout.addWidget(self.btn_quit)
        self.gridLayout_2.addWidget(self.buttons_holder, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.holder_frame, 1, 1, 1, 1)
        self.header = QtWidgets.QFrame(self.main_body)
        self.header.setMinimumSize(QtCore.QSize(0, 50))
        self.header.setStyleSheet("\n"
"")
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 600, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.holder_label = QtWidgets.QFrame(self.header)
        self.holder_label.setStyleSheet("background-color: rgba(85, 170, 255,0);\n"
"border-bottom: 5px solid rgb(18, 1, 116);\n"
"\n"
"")
        self.holder_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.holder_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.holder_label.setObjectName("holder_label")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.holder_label)
        self.gridLayout_3.setContentsMargins(15, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_title = QtWidgets.QLabel(self.holder_label)
        self.lbl_title.setStyleSheet("QLabel{\n"
"    \n"
"    font: 26pt \"Segoe UI Variable Display\";\n"
"    color: rgb(255, 255, 255);    \n"
"    border:none;\n"
"}\n"
"\n"
"\n"
"")
        self.lbl_title.setObjectName("lbl_title")
        self.gridLayout_3.addWidget(self.lbl_title, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.holder_label)
        self.gridLayout.addWidget(self.header, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_custom.setText(_translate("MainWindow", "Customization"))
        self.btn_quit.setText(_translate("MainWindow", "Quit"))
        self.lbl_title.setText(_translate("MainWindow", "Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
